import { headers } from "next/headers";
import { requirePlatformAdmin } from "@/lib/platform-admin";

export const dynamic = "force-dynamic";

type Health = { overall: "online" | "degraded" | "offline"; checks: Record<string, { status: "online" | "degraded" | "offline"; detail: string }>; response_ms: number; checked_at: string };
type Metrics = { generated_at: string; counts: { organisations: number; systems: number; vendors: number; open_actions: number }; recent_audit: { id: string; action: string; entity_type: string; created_at: string }[]; errors: string[] };

async function internalFetch(path: string) {
  const h = await headers(); const host = h.get("x-forwarded-host") ?? h.get("host"); const protocol = h.get("x-forwarded-proto") ?? "https"; const cookie = h.get("cookie");
  if (!host) return null; const r = await fetch(`${protocol}://${host}${path}`, { cache: "no-store", headers: cookie ? { cookie } : undefined }); return r.ok ? r.json() : null;
}

export default async function AdminPage() {
  const access = await requirePlatformAdmin();
  if (!access.ok) return <main className="min-h-screen bg-[#050505] px-6 py-16 text-white"><div className="mx-auto max-w-2xl rounded-2xl border border-white/10 bg-[#0b0b0b] p-8"><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">NEURONBRIGHT Control Plane</p><h1 className="mt-3 text-2xl font-semibold">Access denied</h1><p className="mt-2 text-sm text-white/40">{access.reason}</p></div></main>;
  const [health, metrics] = await Promise.all([internalFetch("/api/admin/health") as Promise<Health | null>, internalFetch("/api/admin/metrics") as Promise<Metrics | null>]);
  const overall = health?.overall ?? "offline";
  return <main className="min-h-screen bg-[#050505] px-6 py-8 text-white xl:px-10"><div className="mx-auto max-w-[1400px]">
    <div className="flex flex-col justify-between gap-5 border-b border-white/10 pb-7 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">Internal platform operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Control Plane</h1><p className="mt-2 text-sm text-white/35">Operational view of the NEURONBRIGHT production platform.</p></div><div className="flex items-center gap-3 rounded-full border border-white/10 bg-white/[0.03] px-4 py-2 text-xs"><span className={`h-2 w-2 rounded-full ${overall === "online" ? "bg-emerald-400" : overall === "degraded" ? "bg-amber-400" : "bg-red-400"}`} /><span className="uppercase tracking-[0.15em] text-white/55">{overall}</span></div></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(health?.checks ?? {}).map(([name, check]) => <div key={name} className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-5"><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-[0.16em] text-white/25">{name}</span><span className={`h-2 w-2 rounded-full ${check.status === "online" ? "bg-emerald-400" : check.status === "degraded" ? "bg-amber-400" : "bg-red-400"}`} /></div><p className="mt-4 text-sm font-medium capitalize">{check.status}</p><p className="mt-2 text-xs leading-5 text-white/30">{check.detail}</p></div>)}</section>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Organisations",metrics?.counts.organisations ?? 0],["AI systems",metrics?.counts.systems ?? 0],["Vendors",metrics?.counts.vendors ?? 0],["Open actions",metrics?.counts.open_actions ?? 0]].map(([label,value])=><div key={label as string} className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-5"><p className="text-[9px] uppercase tracking-[0.16em] text-white/25">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></div>)}</section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_1fr]"><div className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><div className="flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[0.16em] text-white/20">Audit stream</p><h2 className="mt-2 text-lg font-semibold">Recent platform events</h2></div><span className="text-[10px] text-white/20">Live</span></div><div className="mt-5 divide-y divide-white/[0.06]">{(metrics?.recent_audit ?? []).map((event)=><div key={event.id} className="flex items-center justify-between gap-4 py-3 text-xs"><div><p className="text-white/65">{event.action}</p><p className="mt-1 text-[10px] text-white/25">{event.entity_type}</p></div><span className="shrink-0 text-[10px] text-white/25">{new Date(event.created_at).toLocaleString("en-GB")}</span></div>)}{!(metrics?.recent_audit?.length) && <p className="py-4 text-xs text-white/25">No audit events found.</p>}</div></div>
      <div className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><p className="text-[9px] uppercase tracking-[0.16em] text-white/20">Runtime</p><h2 className="mt-2 text-lg font-semibold">Production health</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-[9px] uppercase tracking-[0.14em] text-white/20">Response</p><p className="mt-2 text-sm">{health?.response_ms ?? "—"} ms</p></div><div><p className="text-[9px] uppercase tracking-[0.14em] text-white/20">Checked</p><p className="mt-2 text-sm">{health?.checked_at ? new Date(health.checked_at).toLocaleString("en-GB") : "—"}</p></div><div><p className="text-[9px] uppercase tracking-[0.14em] text-white/20">Admin</p><p className="mt-2 truncate text-sm">{access.user.email}</p></div><div><p className="text-[9px] uppercase tracking-[0.14em] text-white/20">Metric errors</p><p className="mt-2 text-sm">{metrics?.errors.length ?? 0}</p></div></div></div></section>
  </div></main>;
}
