import Link from "next/link";

const regions = [
  { name: "European Union", tag: "EU AI Act", text: "The EU has adopted a horizontal, risk-based AI framework covering prohibited practices, high-risk systems, transparency and governance obligations. Applicability is phased, so organisations need to track which obligations apply to which systems and dates." },
  { name: "United Kingdom", tag: "Sector-led approach", text: "The UK is taking a different route from the EU, combining existing law, regulator responsibilities and emerging AI-specific measures. Data protection, equality, consumer, employment and sector rules can all matter depending on the use case." },
  { name: "United States", tag: "Federal + state", text: "The US has no single comprehensive federal AI Act equivalent to the EU model. Organisations may instead face a mix of federal requirements, agency rules, sector obligations and state laws that continue to develop." },
];

export default function WhyAiGovernancePage() {
  return <main className="min-h-screen bg-[#070707] text-white"><header className="border-b border-white/[0.08]"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">NEURON<span className="text-[#dc6b27]">BRIGHT</span></Link><Link href="/contact" className="rounded-lg bg-[#dc6b27] px-4 py-2 text-sm font-semibold text-black">Talk to us</Link></div></header>
    <section className="mx-auto max-w-6xl px-6 py-20"><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">Why AI governance?</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-[-0.04em] sm:text-6xl">AI adoption is moving faster than governance.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/45">Organisations are putting AI into customer service, HR, finance, software, operations and decision-making. The hard problem is no longer simply writing a policy. It is knowing what is being used, which requirements apply, whether the right controls are operating, and whether you can prove it.</p>
      <div className="mt-16 grid gap-4 lg:grid-cols-3">{regions.map(r=><article key={r.name} className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-7"><p className="text-[10px] uppercase tracking-[0.18em] text-[#dc6b27]">{r.tag}</p><h2 className="mt-3 text-xl font-semibold">{r.name}</h2><p className="mt-4 text-sm leading-7 text-white/40">{r.text}</p></article>)}</div>
    </section>
    <section className="border-y border-white/[0.08] bg-[#0b0b0b]"><div className="mx-auto max-w-6xl px-6 py-16"><p className="text-[10px] uppercase tracking-[0.2em] text-white/30">What this means in practice</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["Requirements","Controls","Owners","Evidence","Assurance"].map((x,i)=><div key={x} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-5"><span className="text-xs text-[#dc6b27]">0{i+1}</span><p className="mt-8 font-medium">{x}</p></div>)}</div><p className="mt-8 max-w-3xl text-white/40 leading-7">NEURONBRIGHT is designed to help organisations operationalise governance obligations. It is not legal advice and does not certify that an organisation is legally compliant. Requirements should be assessed for the organisation, jurisdiction and use case concerned.</p></div></section>
    <section className="mx-auto max-w-6xl px-6 py-16"><h2 className="text-3xl font-semibold">The important distinction</h2><p className="mt-5 max-w-3xl text-white/40 leading-7">A framework can tell you what should happen. NEURONBRIGHT is focused on the operational question: did the control actually run, was it evidenced, and did anything change that should trigger revalidation?</p><p className="mt-8 text-xs text-white/20">Regulatory information on this page is general information, not legal advice. Regulatory requirements and implementation dates can change.</p></section>
  </main>;
}
