"use client";

import { useEffect, useState } from "react";
import { Download, FileText, Printer, RefreshCw } from "lucide-react";
import { AppShell } from "@/components/app-shell";

type Report = { generatedAt: string; summary: { systems: number; controls: number; evidence: number; evidenceCoverage: number; openActions: number; overdueActions: number; highRiskSystems: number; vendors: number; highRiskVendors: number }; systems: { id: string; name: string; risk: string; status: string }[]; vendors: { id: string; name: string; risk: string; status: string }[] };

export default function ReportsPage() {
  const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const r = await fetch("/api/reports/governance", { cache: "no-store" }); if (r.ok) setReport(await r.json()); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const exportJson = () => { if (!report) return; const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `neuronbright-governance-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url); };
  return <AppShell><div className="mx-auto max-w-[1300px] px-6 py-8 print:max-w-none print:px-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end print:hidden"><div><p className="text-[10px] uppercase tracking-[0.18em] text-[#dc6b27]">Executive reporting</p><h1 className="mt-2 text-2xl font-semibold">Governance report</h1><p className="mt-2 text-sm text-white/35">Live governance posture generated from organisation data.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-xs text-white/60"><RefreshCw size={14}/> Refresh</button><button onClick={exportJson} disabled={!report} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-xs text-white/60 disabled:opacity-30"><Download size={14}/> JSON</button><button onClick={() => window.print()} disabled={!report} className="inline-flex items-center gap-2 rounded-lg bg-[#dc6b27] px-4 py-2 text-xs font-semibold text-black disabled:opacity-30"><Printer size={14}/> PDF / Print</button></div></div>
    {loading ? <div className="mt-8 rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-8 text-sm text-white/35">Generating live report…</div> : report ? <><header className="mt-8 border-b border-white/[0.1] pb-6"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.18em] text-[#dc6b27]">NEURONBRIGHT</p><h2 className="mt-2 text-3xl font-semibold">AI Governance Executive Report</h2><p className="mt-2 text-xs text-white/30">Generated {new Date(report.generatedAt).toLocaleString("en-GB")}</p></div><div className="text-right"><p className="text-[9px] uppercase tracking-[0.15em] text-white/25">Evidence coverage</p><p className="mt-1 text-4xl font-semibold text-[#dc6b27]">{report.summary.evidenceCoverage}%</p></div></div></header>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["AI systems",report.summary.systems],["Controls",report.summary.controls],["Evidence",report.summary.evidence],["Open actions",report.summary.openActions],["Overdue actions",report.summary.overdueActions],["High-risk systems",report.summary.highRiskSystems],["Vendors",report.summary.vendors],["High-risk vendors",report.summary.highRiskVendors]].map(([l,v])=><div key={l as string} className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-5"><p className="text-[9px] uppercase tracking-[0.15em] text-white/25">{l}</p><p className="mt-3 text-3xl font-semibold">{v}</p></div>)}</div>
      <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><div className="flex items-center gap-3"><FileText size={17} className="text-[#dc6b27]"/><h3 className="font-semibold">Executive assessment</h3></div><p className="mt-5 text-sm leading-7 text-white/50">NEURONBRIGHT records {report.summary.systems} AI systems, {report.summary.highRiskSystems} high-risk systems and {report.summary.openActions} open governance actions. Evidence coverage is {report.summary.evidenceCoverage}%. Vendor exposure includes {report.summary.vendors} vendors, with {report.summary.highRiskVendors} high-risk.</p></section><section className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><h3 className="font-semibold">Systems requiring attention</h3><div className="mt-4 space-y-2">{report.systems.filter(s=>s.risk === "High" || s.risk === "Critical").slice(0,8).map(s=><div key={s.id} className="flex justify-between rounded-lg bg-white/[0.03] px-3 py-2 text-xs"><span>{s.name}</span><span className="text-[#dc6b27]">{s.risk}</span></div>)}{report.systems.filter(s=>s.risk === "High" || s.risk === "Critical").length === 0 && <p className="text-xs text-white/30">No high-risk systems.</p>}</div></section></div>
      <section className="mt-6 rounded-xl border border-white/[0.08] bg-[#0b0b0b]"><div className="border-b border-white/[0.08] p-6"><h3 className="font-semibold">Vendor exposure</h3></div><div className="divide-y divide-white/[0.07]">{report.vendors.map(v=><div key={v.id} className="flex justify-between px-6 py-3 text-xs"><span>{v.name}</span><span className="text-white/40">{v.risk} · {v.status}</span></div>)}</div></section>
      <p className="mt-6 text-[10px] text-white/20">Operational governance summary. Not legal or regulatory certification.</p>
    </> : <div className="mt-8 rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-8 text-sm text-white/35">Unable to generate report.</div>}
  </div></AppShell>;
}
