"use client";

import { ArrowLeft, ArrowRight, Check, CheckCircle2, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { assessSystem, createPreviewSystem, defaultSystemAssessment, getControlsForSystem, SystemAssessmentForm } from "@/lib/system-assessment";
import { saveSystem } from "@/lib/client-store";
import { saveGovernanceRecord } from "@/lib/governance-store";

type Step = 1 | 2 | 3 | 4;
const dataOptions = ["Names and contact details","Employee information","Customer information","Financial information","Health information","Behavioural data","Performance data","CVs and employment history","Public information","Internal business information"];
const decisionOptions = ["Assistance only","Recommendation","Decision support","Automated decision"] as const;
const oversightOptions = ["Meaningful review","Review available","Limited review","No meaningful review"] as const;
const affectedOptions = ["General population","Employees","Customers","Job applicants","Children","Patients","Vulnerable people"] as const;
const deploymentOptions = ["Internal","Customer-facing","Public-facing"] as const;
const scaleOptions = ["Small","Medium","Large","Enterprise"] as const;

function Field({label,value,placeholder,onChange}:{label:string;value:string;placeholder:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-medium text-white/60">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 h-11 w-full rounded-lg border border-white/[0.08] bg-black px-3 text-xs text-white outline-none placeholder:text-white/15 focus:border-[#dc6b27]/50"/></label>}
function TextArea({label,value,placeholder,onChange}:{label:string;value:string;placeholder:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-medium text-white/60">{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={4} className="mt-2 w-full resize-none rounded-lg border border-white/[0.08] bg-black px-3 py-3 text-xs leading-5 text-white outline-none placeholder:text-white/15 focus:border-[#dc6b27]/50"/></label>}
function Choice({selected,title,onClick}:{selected:boolean;title:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`rounded-lg border p-3 text-left transition ${selected?"border-[#dc6b27]/50 bg-[#dc6b27]/[0.08]":"border-white/[0.08] bg-white/[0.015] hover:border-white/[0.16]"}`}><div className="flex items-center justify-between gap-3"><span className={`text-xs ${selected?"text-white":"text-white/55"}`}>{title}</span><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${selected?"border-[#dc6b27] bg-[#dc6b27] text-black":"border-white/[0.15] text-transparent"}`}><Check size={11}/></span></div></button>}
function Nav({back,next,disabled,nextLabel="Continue",showBack=true}:{back:()=>void;next:()=>void;disabled:boolean;nextLabel?:string;showBack?:boolean}){return <div className="mt-6 flex items-center justify-between border-t border-white/[0.08] pt-5">{showBack?<button type="button" onClick={back} className="inline-flex items-center gap-2 text-xs text-white/35 hover:text-white"><ArrowLeft size={14}/>Back</button>:<span/>}<button type="button" disabled={disabled} onClick={next} className={`inline-flex items-center gap-2 rounded-lg px-5 py-2.5 text-xs font-semibold ${disabled?"cursor-not-allowed bg-white/[0.06] text-white/20":"bg-[#dc6b27] text-black hover:opacity-90"}`}>{nextLabel}<ArrowRight size={14}/></button></div>}

export function SystemAssessment(){
 const router=useRouter(); const [step,setStep]=useState<Step>(1); const [form,setForm]=useState<SystemAssessmentForm>(defaultSystemAssessment);
 const assessment=useMemo(()=>assessSystem(form),[form]); const controls=useMemo(()=>getControlsForSystem(form),[form]);
 function set<K extends keyof SystemAssessmentForm>(field:K,value:SystemAssessmentForm[K]){setForm(c=>({...c,[field]:value}))}
 function toggleData(value:string){setForm(c=>({...c,dataTypes:c.dataTypes.includes(value)?c.dataTypes.filter(x=>x!==value):[...c.dataTypes,value]}))}
 function canContinue(){if(step===1)return !!(form.name.trim()&&form.provider.trim()&&form.owner.trim()&&form.department.trim());if(step===2)return !!(form.purpose.trim()&&form.users.trim()&&form.affectedPeople.trim());if(step===3)return form.affectedCategory!=="Unknown";return form.dataTypes.length>0&&form.decisionType!=="Unknown"&&form.humanOversight!=="Unknown"&&form.deploymentType!=="Unknown"&&form.scale!=="Unknown"}
 function next(){if(canContinue())setStep(c=>(Math.min(4,c+1) as Step))}
 function create(){const system=createPreviewSystem(form,assessment);saveSystem(system);saveGovernanceRecord({systemId:system.id,assessment,controls,createdAt:new Date().toISOString()});router.push(`/systems/${system.id}`)}
 const levelClass=assessment.overallLevel==="High"?"text-[#dc6b27]":assessment.overallLevel==="Medium"?"text-yellow-300":"text-emerald-300";
 return <div className="mx-auto max-w-[1100px] px-6 py-8 xl:px-8">
  <Link href="/systems" className="inline-flex items-center gap-2 text-xs text-white/35 hover:text-white"><ArrowLeft size={14}/>Back to AI systems</Link>
  <div className="mt-7"><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">New AI system</p><h1 className="mt-2 text-2xl font-semibold">Assess an AI system</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/35">Capture the system profile and NEURONBRIGHT will generate an initial risk assessment and governance control plan.</p></div>
  <div className="mt-8 grid gap-2 md:grid-cols-4">{["Identity","Purpose","People","Exposure & assessment"].map((title,i)=><div key={title} className={`rounded-xl border p-4 ${step===i+1?"border-[#dc6b27]/40 bg-[#dc6b27]/[0.06]":i+1<step?"border-emerald-400/20":"border-white/[0.08] bg-[#0b0b0b]"}`}><p className="text-[9px] uppercase tracking-[0.15em] text-white/25">Step {i+1}</p><p className="mt-1 text-xs font-medium text-white/65">{title}</p></div>)}</div>
  {step===1&&<section className="mt-6 rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><div className="grid gap-5 md:grid-cols-2"><Field label="System name" value={form.name} placeholder="Customer Support Copilot" onChange={v=>set("name",v)}/><Field label="Provider" value={form.provider} placeholder="OpenAI / Microsoft / Google / Internal" onChange={v=>set("provider",v)}/><Field label="Model" value={form.model} placeholder="GPT-5 / Claude / Internal model" onChange={v=>set("model",v)}/><Field label="Business owner" value={form.owner} placeholder="Jane Smith" onChange={v=>set("owner",v)}/><Field label="Department" value={form.department} placeholder="Customer Operations" onChange={v=>set("department",v)}/></div><Nav back={()=>{}} next={next} disabled={!canContinue()} showBack={false}/></section>}
  {step===2&&<section className="mt-6 rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><div className="space-y-5"><TextArea label="What does the system do?" value={form.purpose} placeholder="Describe the business purpose and outputs..." onChange={v=>set("purpose",v)}/><Field label="Who uses it?" value={form.users} placeholder="350 customer service employees" onChange={v=>set("users",v)}/><Field label="How could people be affected?" value={form.affectedPeople} placeholder="Customers receiving support and recommendations" onChange={v=>set("affectedPeople",v)}/></div><Nav back={()=>setStep(1)} next={next} disabled={!canContinue()}/></section>}
  {step===3&&<section className="mt-6 rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><p className="text-xs font-medium text-white/60">Who is primarily affected?</p><div className="mt-3 grid gap-2 md:grid-cols-2">{affectedOptions.map(x=><Choice key={x} title={x} selected={form.affectedCategory===x} onClick={()=>set("affectedCategory",x)}/>)}</div><p className="mt-7 text-xs font-medium text-white/60">Sector</p><div className="mt-3 grid gap-2 md:grid-cols-3">{["General business","Employment","Finance","Healthcare","Education","Public sector","Other"].map(x=><Choice key={x} title={x} selected={form.sector===x} onClick={()=>set("sector",x as SystemAssessmentForm["sector"])}/>)}</div><Nav back={()=>setStep(2)} next={next} disabled={!canContinue()}/></section>}
  {step===4&&<section className="mt-6 space-y-5"><div className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><p className="text-xs font-medium text-white/60">What data does it process?</p><div className="mt-3 grid gap-2 md:grid-cols-2">{dataOptions.map(x=><Choice key={x} title={x} selected={form.dataTypes.includes(x)} onClick={()=>toggleData(x)}/>)}</div><p className="mt-7 text-xs font-medium text-white/60">Decision involvement</p><div className="mt-3 grid gap-2 md:grid-cols-2">{decisionOptions.map(x=><Choice key={x} title={x} selected={form.decisionType===x} onClick={()=>set("decisionType",x)}/>)}</div><p className="mt-7 text-xs font-medium text-white/60">Human oversight</p><div className="mt-3 grid gap-2 md:grid-cols-2">{oversightOptions.map(x=><Choice key={x} title={x} selected={form.humanOversight===x} onClick={()=>set("humanOversight",x)}/>)}</div><p className="mt-7 text-xs font-medium text-white/60">Deployment</p><div className="mt-3 grid gap-2 md:grid-cols-3">{deploymentOptions.map(x=><Choice key={x} title={x} selected={form.deploymentType===x} onClick={()=>set("deploymentType",x)}/>)}</div><p className="mt-7 text-xs font-medium text-white/60">Scale</p><div className="mt-3 grid gap-2 md:grid-cols-4">{scaleOptions.map(x=><Choice key={x} title={x} selected={form.scale===x} onClick={()=>set("scale",x)}/>)}</div></div>
   <div className="rounded-xl border border-[#dc6b27]/25 bg-[#dc6b27]/[0.05] p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-[0.18em] text-[#dc6b27]">Initial assessment</p><p className={`mt-2 text-4xl font-semibold ${levelClass}`}>{assessment.overallScore}</p><p className="mt-1 text-xs text-white/30">{assessment.overallLevel} risk</p></div><ShieldAlert className="text-[#dc6b27]" size={30}/></div><div className="mt-5 grid gap-2 md:grid-cols-5">{assessment.dimensions.map(d=><div key={d.name} className="rounded-lg border border-white/[0.07] bg-black/20 p-3"><p className="text-[9px] text-white/25">{d.name}</p><p className="mt-2 text-lg font-semibold">{d.score}</p><p className="text-[9px] uppercase text-white/25">{d.level}</p></div>)}</div></div>
   <div className="rounded-xl border border-white/[0.08] bg-[#0b0b0b] p-6"><div className="flex items-center gap-3"><CheckCircle2 className="text-[#dc6b27]" size={18}/><p className="text-sm font-medium">{controls.length} governance controls will be generated</p></div><p className="mt-2 text-xs text-white/30">Create the system to save the risk assessment and generated control set in this NEURONBRIGHT workspace.</p></div><Nav back={()=>setStep(3)} next={create} nextLabel="Create & assess" disabled={!canContinue()}/></section>}
 </div>
}
