"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Building2, Loader2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import type { OrganisationProfile } from "@/lib/organisation-store";

const emptyProfile: OrganisationProfile = { name:"", industry:"", size:"", governanceLead:"", contactEmail:"" };

export default function SettingsPage(){
 const [profile,setProfile]=useState<OrganisationProfile>(emptyProfile); const [saved,setSaved]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/organisation",{cache:"no-store"}).then(r=>r.json()).then(p=>{if(p.organisation)setProfile({name:p.organisation.name??"",industry:p.organisation.industry??"",size:p.organisation.size??"",governanceLead:p.organisation.governance_lead??"",contactEmail:p.organisation.contact_email??""}); else setError(p.error??"")}).catch(()=>setError("Unable to load organisation.")).finally(()=>setLoading(false))},[]);
 function update<K extends keyof OrganisationProfile>(key:K,value:OrganisationProfile[K]){setProfile(x=>({...x,[key]:value}));setSaved(false)}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setSaved(false);setError("");const r=await fetch("/api/organisation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const p=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(p.error??"Unable to save organisation.");return}setSaved(true)}
 return <AppShell><div className="mx-auto max-w-[1100px] px-6 py-8 xl:px-8"><p className="text-[10px] uppercase tracking-[0.18em] text-[#dc6b27]">Organisation</p><h1 className="mt-2 text-2xl font-semibold">Organisation profile</h1><p className="mt-2 text-sm text-white/35">This is now shared organisation data, not browser-only settings.</p>{error&&<div className="mt-5 rounded-lg border border-[#dc6b27]/20 bg-[#dc6b27]/[0.05] p-3 text-xs text-[#dc6b27]">{error}</div>}<form onSubmit={submit} className="mt-8 rounded-xl border border-white/[0.08] bg-[#0b0b0b]"><div className="flex items-center gap-4 border-b border-white/[0.08] p-6"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#dc6b27]/10"><Building2 size={18} className="text-[#dc6b27]"/></div><div><p className="text-sm font-medium">Organisation identity</p><p className="mt-1 text-xs text-white/25">Changes are persisted in Supabase for your organisation.</p></div></div>{loading?<div className="p-10 text-center text-sm text-white/30">Loading organisation...</div>:<><div className="grid gap-5 p-6 md:grid-cols-2">{([["name","Organisation name"],["industry","Industry"],["size","Organisation size"],["governanceLead","Governance owner"],["contactEmail","Governance contact"]] as const).map(([key,label])=><label key={key} className="block"><span className="text-[10px] uppercase tracking-[0.14em] text-white/25">{label}</span><input value={profile[key]} onChange={e=>update(key,e.target.value)} className="mt-2 w-full rounded-lg border border-white/[0.08] bg-white/[0.025] px-3 py-2.5 text-sm text-white outline-none focus:border-[#dc6b27]/50"/></label>)}</div><div className="flex items-center justify-end gap-4 border-t border-white/[0.08] p-6">{saved&&<span className="flex items-center gap-2 text-xs text-white/40"><CheckCircle2 size={14} className="text-[#dc6b27]"/>Saved</span>}<button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-[#dc6b27] px-5 py-2.5 text-xs font-semibold text-black disabled:opacity-50">{saving&&<Loader2 size={14} className="animate-spin"/>}{saving?"Saving...":"Save organisation"}</button></div></>}</form></div></AppShell>;
}
