import Link from "next/link";

const items = [
  ["Data protection", "We will document the data flows, retention approach, processors and hosting arrangements that apply to the service. Where a control is not yet implemented, we will say so rather than imply it is."],
  ["Access control", "Access should be limited by role and organisation, with privileged operational access separated from customer access."],
  ["Evidence and auditability", "Governance activity is designed to leave a traceable record so teams can understand what was checked and when."],
  ["Security disclosure", "Security questions and responsible disclosure requests can be raised through the contact route while the formal security programme is developed."],
];

export default function SecurityPage(){return <main className="min-h-screen bg-[#070707] text-white"><header className="border-b border-white/[0.08]"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">NEURON<span className="text-[#dc6b27]">BRIGHT</span></Link><Link href="/contact" className="rounded-lg bg-[#dc6b27] px-4 py-2 text-sm font-semibold text-black">Contact</Link></div></header><section className="mx-auto max-w-6xl px-6 py-20"><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">Security & trust</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em]">Governance software has to be trustworthy itself.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/45">NEURONBRIGHT is being built with the same principle it applies to AI governance: make assumptions visible, keep evidence traceable and do not claim a control is working when it has not been demonstrated.</p><div className="mt-14 grid gap-4 md:grid-cols-2">{items.map(([title,text])=><article key={title} className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-7"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-white/40">{text}</p></article>)}</div><div className="mt-12 rounded-2xl border border-[#dc6b27]/20 bg-[#dc6b27]/[0.04] p-7"><h2 className="font-semibold">A note on claims</h2><p className="mt-3 text-sm leading-7 text-white/45">This page describes the product's current approach and intent. It is not a substitute for a security review, contractual commitments, a DPA or customer-specific due diligence. We will publish concrete certifications, attestations and infrastructure details only when they are actually in place.</p></div></section></main>}
