import Link from "next/link";

const plans = [
  { name: "Starter", price: "£299", note: "per month", text: "For teams establishing a governed AI inventory and assurance process.", items: ["AI inventory", "Risk & control mapping", "Evidence tracking", "Action centre", "Core reporting"] },
  { name: "Professional", price: "£999", note: "per month", text: "For organisations operating a broader AI estate with continuous assurance needs.", items: ["Everything in Starter", "Continuous assurance", "Advanced evidence", "Revalidation workflows", "Priority support"] },
  { name: "Enterprise", price: "Custom", note: "talk to us", text: "For larger or regulated organisations with complex environments and integration requirements.", items: ["Everything in Professional", "Custom integrations", "Enterprise controls", "Security review support", "Dedicated onboarding"] },
];

export default function PricingPage(){return <main className="min-h-screen bg-[#070707] text-white"><header className="border-b border-white/[0.08]"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">NEURON<span className="text-[#dc6b27]">BRIGHT</span></Link><Link href="/contact" className="rounded-lg bg-[#dc6b27] px-4 py-2 text-sm font-semibold text-black">Request a demo</Link></div></header><section className="mx-auto max-w-6xl px-6 py-20"><p className="text-[10px] uppercase tracking-[0.2em] text-[#dc6b27]">Pricing</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em]">Start with governance. Scale with assurance.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/45">Simple GBP pricing for organisations that want to know what AI they have, what controls apply and whether those controls are actually operating.</p><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.map(p=><article key={p.name} className="rounded-2xl border border-white/[0.08] bg-[#0b0b0b] p-7"><h2 className="text-xl font-semibold">{p.name}</h2><p className="mt-4 text-4xl font-semibold">{p.price}</p><p className="mt-1 text-xs uppercase tracking-[0.14em] text-white/25">{p.note}</p><p className="mt-6 min-h-14 text-sm leading-6 text-white/40">{p.text}</p><ul className="mt-6 space-y-3">{p.items.map(i=><li key={i} className="text-sm text-white/60">✓ {i}</li>)}</ul><Link href="/contact" className="mt-8 inline-flex rounded-lg border border-white/10 px-4 py-2.5 text-sm">Talk to us</Link></article>)}</div><p className="mt-10 text-xs text-white/20">Pricing is indicative and subject to final plan limits, integrations and contract terms. All prices shown in GBP; taxes may apply.</p></section></main>}
